icons_format = "{icon}"

[theme]
theme = "gruvbox-dark"

[icons]
icons = "awesome4"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "battery"
format = " $percentage {$time |}"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "net"
format = " $icon  {$signal_strength $ssid|Wired connection} "
[[block.click]]
button = "left"
cmd = "urxvt -e sh -c nmtui"

[[block]]
block = "sound"
format = " $icon { $volume|} "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "custom"
command = ""
format = "  "
[[block.click]]
button = "left"
cmd = "systemsettings"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d.%m %R') "
